export default {
  LIST_SKIN_BEING_FETCHED: "LIST_SKIN_BEING_FETCHED",
  LIST_SKIN_FETCHED_SUCCESSFULLY: "LIST_SKIN_FETCHED_SUCCESSFULLY",
  LIST_SKIN_FETCHED_FAILED: "LIST_SKIN_FETCHED_FAILED",
  LIST_CHAMPION_BEING_FETCHED: "LIST_CHAMPION_BEING_FETCHED",
  LIST_CHAMPION_FETCHED_SUCCESSFULLY: "LIST_CHAMPION_FETCHED_SUCCESSFULLY",
  LIST_CHAMPION_FETCHED_FAILED: "LIST_CHAMPION_FETCHED_FAILED"
};
