export const colors = {
  primary: "black",
  green: "#70C1B3",
  seeFoam: "#B2DBBF",
  yellow: "#F3FFBD",
  dangerous: "#FF1654",
  activeRedColor: "red",
  initRedColore: "#901010",
  drawerBackgroundColor: "#111010",
  headerTintColor: "#fff",
  shareIconColor: "#de0000",
  backgroundColorVideo: "#F5FCFF",
  borderColor: "#d6d7da",

  listChampionHearderColor: "#1e3799",
  listChampionHearderLineColor: "#777",
  championAvatarBorderColor: "#00cec9",
  playIconColor: "#e9e9e9",
  redSunset: "#ff3f34",
  closeButtonColor: "#636e72",
  iconSearchColor: "#ffffff",
  underlayColor: "#dfdfdf",
  splashBackGroundColor: "#ecf0f1",
  searchPageTextInput: "#111"
};
